[package]
name = "gptsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
chatgpt_rs = { version = "1.2.3", features = ["functions"] }
clap = { version = "4.5.0", features = ["derive"] }
home = "0.5.9"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.10"
